### ISSUE TITLE
Redefined Constants

### ISSUE THREAD

**Issue by DavidRockin** [garrettw/pierce#2]
In **Numerics\Hybrid.php**, on lines **12 and 22** the `RPL_STATSULINE` constant is defined twice, as well in **Numerics\AustHex.php** on lines **10 and 33** the `RPL_WHOISVIRT` constant is also defined twice.

It is suggested that the duplicate constant to be removed, due to it is resulting in an error to be thrown in PHP.

**Comment by garrettw** [comment]
Wow thanks. Dunno how I keep missing these.
